### ISSUE TITLE
winning conditions

### ISSUE THREAD

**Issue by Swolepenguin** [Swolepenguin/my-cool-game#3]
```function pointCap(){
    if(AI.score <= 10){
    console.log('AI wins')}
    else{console.log("You win")
    }
}
pointCap()
```

**Comment by mkzarra** [comment]
### What's the problem you're trying to solve?

### Relevant code (one fenced block per file or link)
[](url)
### Error messages or unexpected behavior

### Best guess as to the source of the problem

### Steps taken to solve the problem
